version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    # For fix ruby error
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version

      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install RubyGems
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods

      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: sample-ios-swift

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
