version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    # For fix ruby error
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version

      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          - v1-gems-
      - run:
          name: Install RubyGems
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          key: v1-pods-
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods

      - run:
          name: Install SwiftLint
          command: brew install swiftlint

      - run:
          name: Build and run tests
          command: bundle exec fastlane test
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - run:
          name: Run Danger
          command: bundle exec danger

      - store_artifacts:
          path: /Users/distiller/project/output
          destination: output
      - store_test_results:
          path: /Users/distiller/project/output/scan
